---
# tasks file for ansible-molecule-haproxy

- name: Create haproxy directory
  tags: haproxy-dir
  file:
    path: '/etc/haproxy'
    state: directory
    owner: 0
    group: 0
    mode: 0755

- name: Copy volume mapping config file
  tags: haproxy-config
  template:
    src: haproxy.cfg.j2
    dest: '/etc/haproxy/haproxy.cfg'
    owner: 0
    group: 0
    mode: 0644

- name: Create SSL directory
  tags: ssl-dir
  file:
    path: '{{ haproxy_ssl_cert_path }}'
    state: directory
    owner: 0
    group: 0
    mode: 0700
  when: haproxy_ssl_enabled

- name: Copy SSL cert
  tags: ssl
  template:
    src: ssl_cert.j2
    dest: "{{ haproxy_ssl_cert_path }}/{{ haproxy_ssl_cert_file }}"
    owner: 0
    group: 0
    mode: 0600

- name: Run haproxy container
  docker_container:
    name: 'haproxy'
    state: 'started'
    image: "{{ haproxy_docker_image }}"
    volumes: "{{ haproxy_volumes }}"
    ports: "{{ haproxy_docker_expose }}"
